V4: Update supported networks
oceanprotocol/docs pull request #1014
Opened 2022-06-06 09:46 UTC by akshay-ap

Fixes #1011

Changes proposed in this PR:

Updated docs mention support for following production networks:
- [x] Ethereum mainnet
- [x] Moonriver
- [x] BSC

Mention bridge support for:
- [x] BSC
- [x] Moonriver

2022-06-07 05:36 UTC, alexcos20 requested changes

2022-06-07 08:32 UTC, mihaisc commented
I don't see Polygon here

2022-06-07 14:01 UTC, akshay-ap commented
> I don't see Polygon here

Added polygon in the commit here: https://github.com/oceanprotocol/docs/pull/1014/commits/4e35852f4a89c3cf6b3517b5de82bec896ffb6ce.

2022-06-08 08:43 UTC, alexcos20 approved these changes

2022-06-08 08:43 UTC, merged