Issue-#1043: Create hosting aquarius page
oceanprotocol/docs pull request #1055
Opened 2022-07-11 11:16 UTC by akshay-ap

Fixes #1043 

Changes proposed in this PR:

- [x] Create a guide on hosting Aquarius

2022-07-20 09:35 UTC, jamiehewitt15 requested changes
Currently this just covers running Aquarius, can you add an extra section on how to host it? Some info on the options and requirements for hosting would be great (e.g. AWS, Azure, Heroku etc) and it would be good if we could provide the steps for hosting for hosting on at least one of those services. Ideally we want to be able to help someone with zero backend knowledge to quickly get Aquarius hosted

2022-07-25 18:34 UTC, akshay-ap commented
> Currently this just covers running Aquarius, can you add an extra section on how to host it? Some info on the options and requirements for hosting would be great (e.g. AWS, Azure, Heroku etc) and it would be good if we could provide the steps for hosting for hosting on at least one of those services. Ideally we want to be able to help someone with zero backend knowledge to quickly get Aquarius hosted

This is done here in a dedicated page: https://app.gitbook.com/o/mTcjMqA4ylf55anucjH8/s/xUK1Gh4cTFPYiiyojUxw/~/revisions/4bZs8MSwzxaSAjkMSawR/building-with-ocean/deploying-components/setup-server

I created a dedicated page because the setting server steps will be same for deploying Marketplace, Aquarius, Provider and Subgraph.

2022-07-26 07:33 UTC, jamiehewitt15 commented on building-with-ocean/deploying-components/setup-server.md
> +Finalize the parameters for the server, click on `Create Droplet.` After the server is ready, s`e`lect the Access console option from the dropdown.
The `e` in select is formatted wrong

2022-07-26 07:36 UTC, jamiehewitt15 commented on building-with-ocean/deploying-components/setup-server.md
> +A window will open with a terminal session. Now, the required infrastructure is ready for hosting Aquarius. Let's install docker and docker-compose on the server. Follow the installation guide [here]
```suggestion
A window will open with a terminal session. Now, the required infrastructure is ready for hosting Aquarius, Provider or the Subgraph. Let's install docker and docker-compose on the server. Follow the installation guide [here](https://docs.docker.com/engine/install/ubuntu/).
```

2022-07-26 09:20 UTC, jamiehewitt15 approved these changes
Looks good to me

2022-07-26 09:25 UTC, merged