Issue 908 spelling issues
oceanprotocol/docs pull request #911
Opened 2022-03-04 11:57 UTC by akshay-ap

Fixes #908

Changes proposed in this PR:

- [x] https://deploy-preview-819--docs-oceanprotocol.netlify.app/concepts/architecture/
- [ ] https://deploy-preview-819--docs-oceanprotocol.netlify.app/concepts/datanft-and-datatoken/
- [ ] https://deploy-preview-819--docs-oceanprotocol.netlify.app/concepts/did-ddo/

2022-03-08 17:31 UTC, AnaLoznianu commented
On the Architecture page, there is an image that has some mistakes.
![Uploading Screenshot 2022-03-08 at 19.26.56.png…]()

2022-03-08 17:39 UTC, AnaLoznianu commented
On the DataNFTs and Datatokens page the same, we need to update the image
![Uploading Screenshot 2022-03-08 at 19.37.55.png…]()

2022-03-08 17:46 UTC, AnaLoznianu commented
I noticed that, in some places we have MetaData, in others, we have Metadata. Let's use all over the places the same, please. Thank you!

2022-03-08 17:46 UTC, AnaLoznianu requested changes

2022-03-08 17:46 UTC, AnaLoznianu commented on content/concepts/architecture.md
> +Ocean uses the Ethereum mainnet and other compatible networks as an **on-chain metadata store**, i.e. to store both DID and DDO. This means that once the transaction fee is paid, there are no further
I think is devops, without a hyphen.
Also on the tradeoff, we need one...it is tradeoff

2022-03-08 17:46 UTC, AnaLoznianu commented on content/concepts/architecture.md
> +Due to the permissionless, decentralized nature of data on the Ethereum mainnet, any last-mile tool can access metadata. **Ocean Aquarius** supports different metadata fields for each different Ocean
last-mile without a hyphen please

2022-03-09 15:39 UTC, akshay-ap commented
> On the Architecture page, there is an image that has some mistakes. ![Screenshot 2022-03-08 at 19 26 56](https://user-images.githubusercontent.com/84312885/157295676-5ca57849-a3e6-4c5b-9b8a-3c431c1f8543.png)

Pushed commit with updated image https://github.com/oceanprotocol/docs/pull/911/commits/54ec6159372ebd1fff95ca5c6a85a3b2cd34748e

2022-03-09 16:02 UTC, akshay-ap commented
> On the DataNFTs and Datatokens page the same, we need to update the image ![Screenshot 2022-03-08 at 19 37 55](https://user-images.githubusercontent.com/84312885/157295739-9f4f9f8d-b50e-4781-bea0-e83d66134281.png)
> 
> On the High-Level Behavior section, I'm not sure if what I've underlined here is an issue or not ![high-level](https://user-images.githubusercontent.com/84312885/157294852-f8c832df-cfbe-424b-946f-875929ec2a2b.jpeg)

`datanft-and-datatoken.png` image fixed here: https://github.com/oceanprotocol/docs/pull/911/commits/a501c142dac2be0cd69253c08c561f4b628c36ac

2022-03-10 16:59 UTC, merged