Issue-#912: V4 publish tutorial
oceanprotocol/docs pull request #957
Opened 2022-04-07 20:46 UTC by akshay-ap

Fixes #912

Changes proposed in this PR:

- [x] V4 Publish tutorial
- [ ] V4 Consume tutorial
- [ ] V4 Swap and stake tutorial

2022-04-11 10:53 UTC, AnaLoznianu commented
@akshay-ap I think we can improve a bit the publish flow. These are some ideas:
* "Step 1 - **Fill metadata**". Maybe **"Fill in metadata"**? Let's provide some information on the fields and also mention which ones can be edited after the asset is published.
* "Step 2 - **Fill access details"**. Maybe **"Fill in access details"?** The same, let's provide some info on the fields. Also, mention which are required and which are not.
* "Step 3 - Set pricing". the text for this section is personal and non-personal. I suggest changing this line: "Here, we are selecting dynamic pricing." to "Flow for dynamic pricing schema"
* "Step 5 - Send blockchain transactions". Here the captions seem to be connected to the next step but actually, they represent the previous step. Can we get the captions closer to the right transaction they represent? 
* "Confirmation". I suggest changing the label: "Now, after the transactions are completed, the below screen will appear." to "Once the transactions are completed, the below screen is displayed." 

I would remove the links towards a specific transaction. It might create confusion. 
"To view Create tokens and pricing transaction on testnet click [here](https://rinkeby.etherscan.io/tx/0x599a506d8429e3bd8b827f7ad2ca893ca866c8259a17d88b352c0345842e67d0)
To view Publish DDO transaction on testnet click [here](https://rinkeby.etherscan.io/tx/0x8d1a1f0d833f4e46432351d16013bb4fcdd6b05e65a2fe3e599f3a90e4d35478)
To view published the asset on Ocean Market click [here](https://v4.market.oceanprotocol.com/asset/did:op:63920bb64ad1e79bed73214e5fd574fc68c0977cdba5b7031aa98a3a83e28197)"

2022-04-12 07:47 UTC, AnaLoznianu requested changes

2022-04-12 14:22 UTC, AnaLoznianu commented on content/tutorials/marketplace-download-data-asset.md
> +### Step 4: Click buy button
Here the button is download

2022-04-12 14:22 UTC, AnaLoznianu commented on content/tutorials/marketplace-download-data-asset.md
> +### Step 3: Buy datatoken by exchanging it with Ocean token(s)
Buy "a" datatoken

2022-04-12 14:22 UTC, AnaLoznianu commented on content/tutorials/marketplace-download-data-asset.md
> +### Step 1: Click buy button
Click "on the buy" button

2022-04-12 14:22 UTC, AnaLoznianu commented on content/tutorials/marketplace-publish-data-asset.md
> +### Connecting wallet and navigating to publish page
navigating to "the" publish page

2022-04-12 14:22 UTC, AnaLoznianu commented on content/tutorials/marketplace-publish-data-asset.md
> +Fill the metadata.
Fill "in" the metadata

2022-04-12 14:22 UTC, AnaLoznianu commented on content/tutorials/marketplace-swap-and-stake.md
>  ## Swap OCEAN Tokens against datatokens
Swap OCEAN "tokens" against datatokens

2022-04-12 14:22 UTC, AnaLoznianu commented on content/tutorials/marketplace-swap-and-stake.md
> +### Step 1: Understanding the risks
I would rename this step to "Agree with the risks associated".. Also with a description:
"Please read carefully the risks associated with this operation and agree to move forward"

2022-04-12 14:22 UTC, AnaLoznianu commented on content/tutorials/marketplace-swap-and-stake.md
> +![staking part-2](images/marketplace/Staking-2.png 'Enter amount of Oceans')
This image doesn't load

2022-04-12 14:22 UTC, AnaLoznianu commented on content/tutorials/marketplace-swap-and-stake.md
>  ## Staking (Adding Liquidity)
The liquidity pool tab will change a little bit. We already have a PR opened: https://github.com/oceanprotocol/market/pull/1327.
Let's please wait to have that merged and then we can update the images as well. Thanks

2022-04-13 12:45 UTC, akshay-ap commented on content/tutorials/marketplace-swap-and-stake.md
> +![staking part-2](images/marketplace/Staking-2.png 'Enter amount of Oceans')
Might be an issue with the cache.

2022-04-14 11:53 UTC, AnaLoznianu commented
@trentmc @alexcos20 Should we use the stake term in these tutorials? Or "Add liquidity" is more appropriate?

2022-04-19 10:38 UTC, AnaLoznianu approved these changes

2022-04-19 10:38 UTC, alexcos20 approved these changes
lgtm

2022-04-19 15:18 UTC, merged