Fix grammer issue
oceanprotocol/docs pull request #984
Opened 2022-05-10 10:58 UTC by akshay-ap

Fixes #982 

Changes proposed in this PR:

- [x] Fix grammar issue
- [ ] Fix ambiguity in text

2022-05-16 13:59 UTC, AnaLoznianu requested changes

2022-05-16 13:59 UTC, AnaLoznianu commented on content/concepts/did-ddo.md
> +- The dataset publisher wants to know the desired sampling interval of data before the buyer downloads it. Suppose the dataset URL is `https://example.com/mydata`. So the publisher will define a fiel
Suggestion: "Sometimes, the asset needs additional input data before downloading a dataset or running an algorithm.
The publisher needs to know the sampling interval before the buyer downloads it. Suppose the dataset URL is `https://example.com/mydata'. The publisher then defines a field called `sampling` and asks the buyer to enter a value. This parameter is added to the URL of the published dataset as query parameters: `https://example.com/mydata?sampling=10`."

2022-05-16 13:59 UTC, AnaLoznianu commented on content/concepts/did-ddo.md
> +- Before running an algorithm, the algorithm needs to know how many iterations should it perform. In this case, the algorithm publisher defines a field called `iterations`. The buyer enters the value
Suggestion: "An algorithm that needs to know how many iterations should perform. In this case, the algorithm publisher defines a field called `iterations`. The buyer needs to enter a value for the `iterations` parameter. Later, this value is stored in a specific location in the Computer-to-Data pod for the algorithm to read and use it."

2022-05-17 07:59 UTC, AnaLoznianu requested changes

2022-05-17 07:59 UTC, AnaLoznianu commented on content/concepts/did-ddo.md
> +- Sometimes, the asset needs additional input data before downloading a dataset or running an algorithm. The publisher needs to know the sampling interval before the buyer downloads it. Suppose the d
@akshay-ap We have the sometimes sentence twice now. 
![Screenshot 2022-05-17 at 10 56 50](https://user-images.githubusercontent.com/84312885/168759895-08656564-458c-4c7a-96dd-8bd7b44f31de.png)

Please adjust the first sentence with the suggestion I offered.
Also, please add the proper formatting for the 'sampling' parameter

2022-05-17 09:21 UTC, trentmc commented
Note: I just fixed the spelling issue in "fix grammer issue". It kept nagging me 🤷‍♂️ :)

2022-05-17 09:29 UTC, akshay-ap commented
> Note: I just fixed the spelling issue in "fix grammer issue". It kept nagging me man_shrugging :)

apologies for the inconvenience 😞

2022-05-17 10:15 UTC, AnaLoznianu approved these changes

2022-05-17 10:17 UTC, merged